"""
Type definitions and schemas for the Netra Profiler Data Contract.

This module defines the strict hierarchical output structure (NetraProfile)
generated by the engine, corresponding to the netra_profile_schema_v1.json specification.
"""

from typing import Any, TypedDict


class DatasetMeta(TypedDict):
    """Metadata describing the ingested dataset."""

    name: str
    format: str
    row_count: int


class ExecutionMeta(TypedDict):
    """Telemetry and metadata regarding the profiler's execution environment and performance."""

    created_at: str
    execution_start_epoch: float
    execution_end_epoch: float
    engine_time_seconds: float
    profiler_version: str
    warnings: list[str]


class ColumnMetrics(TypedDict, total=False):
    """
    Comprehensive statistical profile for a single column.

    Note: total=False is used because numeric and string columns have
    mutually exclusive fields (e.g., 'mean' vs 'mean_length').
    """

    data_type: str
    null_count: int
    n_unique: int
    histogram: list[dict[str, Any]]
    top_k: list[dict[str, Any]]

    # Numeric & String Shared Metrics
    min: float | int | str | None
    max: float | int | str | None

    # Numeric Specific
    mean: float | None
    std: float | None
    skew: float | None
    kurtosis: float | None
    p25: float | None
    p50: float | None
    p75: float | None

    # String Specific
    min_length: int | None
    max_length: int | None
    mean_length: float | None


class CorrelationPair(TypedDict):
    """Represents a single edge in the de-duplicated correlation matrix."""

    column_a: str
    column_b: str
    score: float


class CorrelationData(TypedDict):
    """Container for the correlation matrices and the sampling methodology."""

    pearson: list[CorrelationPair]
    spearman: list[CorrelationPair]
    sampling_method: str | None


class DiagnosticAlert(TypedDict):
    """A data quality anomaly detected by the DiagnosticEngine."""

    column_name: str
    type: str
    level: str  # "CRITICAL", "WARNING", "INFO"
    message: str
    value: float | int | None


class NetraProfile(TypedDict):
    """The root schema for the Netra Profiler Data Contract."""

    dataset: DatasetMeta
    columns: dict[str, ColumnMetrics]
    correlations: CorrelationData
    alerts: list[DiagnosticAlert]
    _meta: ExecutionMeta


# --- Type Inference Utilities ---


def is_numeric(data_type: str) -> bool:
    """
    Determines if a Polars stringified data type belongs to a numeric family.

    Args:
        data_type: The string representation of a Polars datatype (e.g., "Int64", "Float32").
    """
    # Logic: if "Int" in "Int64": return True
    return any(base_type in data_type for base_type in ["Int", "Float", "Decimal"])


def is_string_type(data_type: str) -> bool:
    """
    Determines if a Polars stringified data type belongs to a text/categorical family.

    Args:
        data_type: The string representation of a Polars datatype (e.g., "Utf8", "Enum").
    """
    if not data_type:
        return False
    return any(base_type in data_type for base_type in ["String", "Utf8", "Categorical", "Enum"])
